### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by Default4152** [nasseralrayes/Jammming#7]
GRADE: Needs improvement

I really like how clean your code was in this project. It really was easy to look over and debug. The spacing and indentation was almost perfect throughout the entire project. I also noticed your usage of console.log for debugging, that was a great idea! A couple of things I would work on is making sure all errors and bugs are out of the application so that it can be properly tested. I was able to get your application up and running, but there were quite a few errors in the functionality. After addressing all of these errors, feel free to improve your project more by using the assistance of something like a linter (eslint). 

https://eslint.org/
https://github.com/facebook/react-devtools
https://medium.com/@baphemot/intro-to-debugging-reactjs-applications-67cf7a50b3dd

**Comment by nasseralrayes** [comment]
Thanks so much, Conner! I got it almost working perfectly now. The only thing I'm struggling with is having the playlist name reset to "New Playlist" and displaying that after I save a new playlist. Although internally that's the name it is being saved as, it is not displaying the name change on the browser. I've noticed the demo version we were given doesn't do that either, however. Anyways, I'll fiddle with it a little longer and see what I can do. Thanks again!
